#include "task_queue.h"
#include "sys.h"

#include <algorithm>
#include <cerrno>
#include <charconv>
#include <climits>
#include <dirent.h>
#include <fcntl.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <unistd.h>

namespace task_queue {
namespace {
constexpr size_t id_bytes=32, id_length=id_bytes*2, target_max=4096, failure_max=256;
constexpr u64 max_capacity=100000, max_bytes=16*1024*1024, max_wait_ms=24ULL*60*60*1000, max_retention_seconds=365ULL*24*60*60;
#ifdef TASK_QUEUE_TESTING
bool claim_crash_after_rename=false;
#endif
struct Lock { int fd=-1; Lock(const String& p) { fd=open(p.c_str(),O_RDWR|O_CREAT|O_CLOEXEC|O_NOFOLLOW,0600); if(fd>=0) { int r; do r=flock(fd,LOCK_EX); while(r&&errno==EINTR); if(r) { close(fd); fd=-1; } } } ~Lock() { if(fd>=0) { flock(fd,LOCK_UN); close(fd); } } bool ok() const { return fd>=0; } };
bool valid_limits(const Limits& l) { return l.capacity&&l.capacity<=max_capacity&&l.payload_max&&l.payload_max<=max_bytes&&l.retention_seconds<=max_retention_seconds&&l.scan_max>=l.capacity&&l.scan_max<=max_capacity&&l.status_max&&l.status_max<=max_bytes&&l.await_max_ms&&l.await_max_ms<=max_wait_ms; }
bool decimal(const String& s,u64& n) { if(s.empty())return false;for(char c:s)if(c<'0'||c>'9')return false;auto r=std::from_chars(s.data(),s.data()+s.size(),n);return r.ec==std::errc()&&r.ptr==s.data()+s.size(); }
bool opaque_id(const String& s) { if(s.size()!=id_length)return false;for(char c:s)if(!((c>='0'&&c<='9')||(c>='a'&&c<='f')))return false;return true; }
bool target_valid(const String& s) { if(s.empty()||s.size()>target_max)return false;for(unsigned char c:s)if(c<0x20||c==0x7f)return false;return true; }
String hex_id() { String b=random_bytes(id_bytes),out;if(b.size()!=id_bytes)return "";static const char h[]="0123456789abcdef";out.reserve(id_length);for(unsigned char c:b){out+=h[c>>4];out+=h[c&15];}return out; }
String now_ms() { timespec ts{};return clock_gettime(CLOCK_REALTIME,&ts)?"0":std::to_string((u64)ts.tv_sec*1000+(u64)ts.tv_nsec/1000000); }
u64 monotonic_ms() { timespec ts{};return clock_gettime(CLOCK_MONOTONIC,&ts)?0:(u64)ts.tv_sec*1000+(u64)ts.tv_nsec/1000000; }
String join(const String&a,const String&b){return a+"/"+b;} String join(const String&a,const String&b,const String&c){return join(join(a,b),c);}
bool directory(const String&p){struct stat s{};return !lstat(p.c_str(),&s)&&S_ISDIR(s.st_mode);} bool make_directory(const String&p){return (mkdir(p.c_str(),0700)==0||errno==EEXIST)&&directory(p);}
bool fsync_directory(const String&p){int fd=open(p.c_str(),O_RDONLY|O_DIRECTORY|O_CLOEXEC);bool ok=fd>=0&&fsync(fd)==0;if(fd>=0)close(fd);return ok;} bool prepare(const String&r){return make_directory(r)&&make_directory(join(r,"pending"))&&make_directory(join(r,"running"))&&make_directory(join(r,"status"))&&make_directory(join(r,"index"));}
bool write_all(int fd,const String&s){for(size_t at=0;at<s.size();){ssize_t n=write(fd,s.data()+at,s.size()-at);if(n<0&&errno==EINTR)continue;if(n<=0)return false;at+=(size_t)n;}return true;}
bool publish(const String&dir,const String&name,const String&text){String nonce=hex_id();if(nonce.empty())return false;String temp=join(dir,"."+name+"."+nonce+".tmp"),final=join(dir,name);int fd=open(temp.c_str(),O_WRONLY|O_CREAT|O_EXCL|O_CLOEXEC,0600);if(fd<0)return false;bool ok=write_all(fd,text)&&fsync(fd)==0;if(close(fd))ok=false;if(!ok){unlink(temp.c_str());return false;}if(rename(temp.c_str(),final.c_str())){unlink(temp.c_str());return false;}return fsync_directory(dir);}
bool move_file(const String&from_dir,const String&name,const String&to_dir){if(rename(join(from_dir,name).c_str(),join(to_dir,name).c_str()))return false;return fsync_directory(from_dir)&&(from_dir==to_dir||fsync_directory(to_dir));}
bool remove_file(const String&dir,const String&name){return !unlink(join(dir,name).c_str())&&fsync_directory(dir);}
bool publish_index(const String&root,const String&id,const String&dir,const String&name){return publish(join(root,"index"),id+".task",dir+"\n"+name);}
bool remove_index(const String&root,const String&id){String dir=join(root,"index");if(unlink(join(dir,id+".task").c_str())!=0&&errno!=ENOENT)return false;return fsync_directory(dir);}
bool read_file(const String&p,size_t max,String&out){struct stat s{};if(lstat(p.c_str(),&s)||!S_ISREG(s.st_mode)||s.st_size<0||(u64)s.st_size>max)return false;int fd=open(p.c_str(),O_RDONLY|O_CLOEXEC|O_NOFOLLOW);if(fd<0)return false;out.resize((size_t)s.st_size);size_t at=0;while(at<out.size()){ssize_t n=read(fd,&out[at],out.size()-at);if(n<0&&errno==EINTR)continue;if(n<=0){close(fd);return false;}at+=(size_t)n;}return close(fd)==0;}
std::vector<String> records(const String&dir,u64 max,bool&complete,bool sort_names=true){std::vector<String>out;complete=false;DIR*d=opendir(dir.c_str());if(!d)return out;while(dirent*e=readdir(d)){String n=e->d_name;if(n.size()>5&&n.ends_with(".task")){if(out.size()>=max){closedir(d);return out;}out.push_back(n);}}closedir(d);complete=true;if(sort_names)std::sort(out.begin(),out.end());return out;}
bool sequence_name(const String&name,String&seq,String&id){if(name.size()!=20+1+id_length+5||name[20]!='-'||!name.ends_with(".task"))return false;seq=name.substr(0,20);u64 n=0;id=name.substr(21,id_length);return decimal(seq,n)&&seq.size()==20&&opaque_id(id);}
bool status_name(const String&name,String&id){if(name.size()!=id_length+5||!name.ends_with(".task"))return false;id=name.substr(0,id_length);return opaque_id(id);}
const DValue& field(const DValue&v,const String&n){static const DValue empty;const DValue*f=v.key(n);return f?*f:empty;}
DValue record_value(const String&id,const String&target,const DValue&props,const String&seq,u64 attempt,const String&created){DValue r;r["id"]=id;r["target"]=target;r["props"]=props;r["sequence"]=seq;r["attempt"]=std::to_string(attempt);r["created_ms"]=created;r["lease_id"]="";r["cancel_requested"].set_bool(false);r["failure_code"]="";return r;}
bool parse_record(const String&raw,size_t max,DValue&r){if(raw.size()>max||!brb_decode(raw,r,0)||r.type!='M')return false;u64 attempt=0,seq=0,created=0;const DValue*props=r.key("props");return opaque_id(field(r,"id").to_string())&&target_valid(field(r,"target").to_string())&&props&&decimal(field(r,"attempt").to_string(),attempt)&&decimal(field(r,"sequence").to_string(),seq)&&field(r,"sequence").to_string().size()==20&&decimal(field(r,"created_ms").to_string(),created)&&(!field(r,"lease_id").to_string().empty()?opaque_id(field(r,"lease_id").to_string()):true)&&field(r,"cancel_requested").type=='B'&&field(r,"failure_code").to_string().size()<=failure_max;}
bool terminal(const String&s){return s=="succeeded"||s=="failed"||s=="canceled";}
DValue status_value(const DValue&r,const String&state,const String&completed=""){DValue s;s["id"]=field(r,"id").to_string();s["state"]=state;s["target"]=field(r,"target").to_string();s["attempt"]=field(r,"attempt").to_string();s["created_ms"]=field(r,"created_ms").to_string();s["failure_code"]=field(r,"failure_code").to_string();s["cancel_requested"].set_bool(field(r,"cancel_requested").to_bool());s["done"].set_bool(terminal(state));if(terminal(state))s["completed_ms"]=completed.empty()?now_ms():completed;return s;}
DValue missing_value(const String&id){DValue s;s["id"]=id;s["state"]="missing";s["done"].set_bool(false);return s;}
Result error(const String&code){Result r;r.code=code;return r;} Result ok_status(const DValue&s){Result r;r.code="ok";r.status=s;return r;}
bool valid_failure(const String&s){if(s.empty()||s.size()>failure_max)return false;for(char c:s)if(!((c>='a'&&c<='z')||(c>='0'&&c<='9')||c=='_'))return false;return true;}
bool publish_failed(const String&root,const Limits&l,const String&id,const DValue*record=nullptr){DValue r;if(record)r=*record;else{r["id"]=id;r["attempt"]="0";r["created_ms"]=now_ms();r["cancel_requested"].set_bool(false);}r["failure_code"]="malformed_record";String data=brb_encode(status_value(r,"failed"));return data.size()<=l.status_max&&publish(join(root,"status"),id+".task",data);}
bool quarantine(const String&root,const Limits&l,const String&dir,const String&name){String raw,id,seq;DValue r;bool parsed=read_file(join(dir,name),l.payload_max+l.status_max,raw)&&parse_record(raw,l.payload_max+l.status_max,r);if(parsed)id=field(r,"id").to_string();else if(!sequence_name(name,seq,id))id=hex_id();if(id.empty())return false;if(access(join(join(root,"status"),id+".task").c_str(),F_OK)==0)return remove_file(dir,name);if(!publish_failed(root,l,id,parsed?&r:nullptr))return false;return remove_file(dir,name);}
bool parse_status(const String&raw,size_t max,DValue&s,const String&expected_id=""){u64 completed=0;return raw.size()<=max&&brb_decode(raw,s,0)&&s.type=='M'&&opaque_id(field(s,"id").to_string())&&(expected_id.empty()||field(s,"id").to_string()==expected_id)&&terminal(field(s,"state").to_string())&&field(s,"done").type=='B'&&field(s,"done").to_bool()&&decimal(field(s,"completed_ms").to_string(),completed);}
Result status_locked(const String&root,const Limits&l,const String&id){String raw;DValue r;String status_dir=join(root,"status");if(read_file(join(status_dir,id+".task"),l.status_max,raw)){if(!parse_status(raw,l.status_max,r,id)){if(!publish_failed(root,l,id))return error("storage_error");return status_locked(root,l,id);}return ok_status(r);}String locator;if(read_file(join(root,"index",id+".task"),256,locator)){size_t newline=locator.find('\n');String dir=newline==String::npos?String(""):locator.substr(0,newline),name=newline==String::npos?String(""):locator.substr(newline+1),seq,found;if((dir=="pending"||dir=="running")&&sequence_name(name,seq,found)&&found==id&&read_file(join(root,dir,name),l.payload_max+l.status_max,raw)&&parse_record(raw,l.payload_max+l.status_max,r))return ok_status(status_value(r,dir=="pending"?"queued":"running"));remove_index(root,id);}for(const String&dir:{String("pending"),String("running")}){bool complete;auto names=records(join(root,dir),l.scan_max,complete,false);if(!complete)return error("scan_limit");for(const String&name:names){String seq,found;if(!sequence_name(name,seq,found)||found!=id)continue;if(!read_file(join(root,dir,name),l.payload_max+l.status_max,raw)||!parse_record(raw,l.payload_max+l.status_max,r)){if(!quarantine(root,l,join(root,dir),name))return error("storage_error");return status_locked(root,l,id);}return ok_status(status_value(r,dir=="pending"?"queued":"running"));}}return ok_status(missing_value(id));}
}
#ifdef TASK_QUEUE_TESTING
void set_claim_crash_after_rename_for_test(bool enabled){claim_crash_after_rename=enabled;}
#endif

Result submit(const String&root,const Limits&l,const String&target,const DValue&props){if(!valid_limits(l)||!target_valid(target))return error("invalid_input");String payload=brb_encode(props);if(payload.size()>l.payload_max)return error("payload_too_large");if(!prepare(root))return error("storage_error");Lock lock(join(root,"lock"));if(!lock.ok())return error("lock_error");bool a,b;auto pending=records(join(root,"pending"),l.scan_max,a,false),running=records(join(root,"running"),l.scan_max,b,false);if(!a||!b)return error("scan_limit");if(pending.size()+running.size()>=l.capacity)return error("queue_full");u64 next=0;String counter;if(read_file(join(root,"sequence"),32,counter)){if(!decimal(counter,next)||next==ULLONG_MAX)return error("malformed_sequence");}else{struct stat st{};if(!lstat(join(root,"sequence").c_str(),&st))return error("malformed_sequence");}++next;String seq=std::to_string(next);if(seq.size()>20)return error("sequence_exhausted");seq=String(20-seq.size(),'0')+seq;String id=hex_id();if(id.empty())return error("random_error");String data=brb_encode(record_value(id,target,props,seq,0,now_ms()));if(data.size()>l.payload_max+l.status_max)return error("payload_too_large");String name=seq+"-"+id+".task";if(!publish(root,"sequence",std::to_string(next))||!publish(join(root,"pending"),name,data))return error("storage_error");if(!publish_index(root,id,"pending",name)){remove_file(join(root,"pending"),name);return error("storage_error");}Result out;out.code="ok";out.task.id=id;out.status=missing_value(id);out.status["state"]="queued";return out;}

Result claim(const String&root,const Limits&l,const String&lease){if(!valid_limits(l)||!opaque_id(lease)||!prepare(root))return error("invalid_input");Lock lock(join(root,"lock"));if(!lock.ok())return error("lock_error");bool complete;auto names=records(join(root,"pending"),l.scan_max,complete);if(!complete)return error("scan_limit");for(const String&name:names){String raw,seq,id;DValue r;if(!sequence_name(name,seq,id)||!read_file(join(root,"pending",name),l.payload_max+l.status_max,raw)||!parse_record(raw,l.payload_max+l.status_max,r)){if(!quarantine(root,l,join(root,"pending"),name))return error("storage_error");continue;}if(access(join(join(root,"status"),id+".task").c_str(),F_OK)==0){if(!remove_file(join(root,"pending"),name))return error("storage_error");continue;}
		// Rename is the ownership transfer: after this point recovery sees one orphaned running file, never two live records.
		if(!move_file(join(root,"pending"),name,join(root,"running")))return error("storage_error");
#ifdef TASK_QUEUE_TESTING
		if(claim_crash_after_rename)return error("injected_crash");
#endif
		u64 attempt=field(r,"attempt").to_u64()+1;r["attempt"]=std::to_string(attempt);r["lease_id"]=lease;String data=brb_encode(r);if(data.size()>l.payload_max+l.status_max||!publish_index(root,id,"running",name)||!publish(join(root,"running"),name,data)){publish_index(root,id,"pending",name);move_file(join(root,"running"),name,join(root,"pending"));return error("storage_error");}Result out;out.code="ok";out.task={id,field(r,"target").to_string(),field(r,"props"),lease,attempt};out.status=status_value(r,"running");return out;}return error("empty");}

Result succeed(const String&root,const Limits&l,const String&id,const String&lease){if(!valid_limits(l)||!opaque_id(id)||!opaque_id(lease)||!prepare(root))return error("invalid_input");Lock lock(join(root,"lock"));if(!lock.ok())return error("lock_error");bool complete;auto names=records(join(root,"running"),l.scan_max,complete,false);if(!complete)return error("scan_limit");for(const String&name:names){String seq,found,raw;DValue r;if(!sequence_name(name,seq,found)||found!=id)continue;if(!read_file(join(root,"running",name),l.payload_max+l.status_max,raw)||!parse_record(raw,l.payload_max+l.status_max,r)){if(!quarantine(root,l,join(root,"running"),name))return error("storage_error");return status_locked(root,l,id);}if(field(r,"lease_id").to_string()!=lease)return error("lease_mismatch");String state=field(r,"cancel_requested").to_bool()?"canceled":"succeeded",data=brb_encode(status_value(r,state));if(data.size()>l.status_max||!publish(join(root,"status"),id+".task",data)||!remove_file(join(root,"running"),name))return error("storage_error");return ok_status(status_value(r,state));}return status_locked(root,l,id);}

Result fail(const String&root,const Limits&l,const String&id,const String&lease,const String&failure){if(!valid_limits(l)||!opaque_id(id)||!opaque_id(lease)||!valid_failure(failure)||!prepare(root))return error("invalid_input");Lock lock(join(root,"lock"));if(!lock.ok())return error("lock_error");bool complete;auto names=records(join(root,"running"),l.scan_max,complete,false);if(!complete)return error("scan_limit");for(const String&name:names){String seq,found,raw;DValue r;if(!sequence_name(name,seq,found)||found!=id)continue;if(!read_file(join(root,"running",name),l.payload_max+l.status_max,raw)||!parse_record(raw,l.payload_max+l.status_max,r)){if(!quarantine(root,l,join(root,"running"),name))return error("storage_error");return status_locked(root,l,id);}if(field(r,"lease_id").to_string()!=lease)return error("lease_mismatch");r["failure_code"]=failure;String state=field(r,"cancel_requested").to_bool()?"canceled":"failed",data=brb_encode(status_value(r,state));if(data.size()>l.status_max||!publish(join(root,"status"),id+".task",data)||!remove_file(join(root,"running"),name))return error("storage_error");return ok_status(status_value(r,state));}return status_locked(root,l,id);}

Result status(const String&root,const Limits&l,const String&id){if(!valid_limits(l)||!opaque_id(id)||!prepare(root))return error("invalid_input");Lock lock(join(root,"lock"));return lock.ok()?status_locked(root,l,id):error("lock_error");}
Result await(const String&root,const Limits&l,const String&id,u64 timeout_ms,u64 poll_ms){if(!valid_limits(l)||!opaque_id(id)||!poll_ms||timeout_ms>l.await_max_ms||poll_ms>l.await_max_ms)return error("invalid_input");u64 start=monotonic_ms();for(;;){Result r=status(root,l,id);if(!r.ok()||terminal(field(r.status,"state").to_string()))return r;u64 now=monotonic_ms();if(now<start||now-start>=timeout_ms)return r;u64 wait=std::min(poll_ms,timeout_ms-(now-start));usleep((useconds_t)std::min<u64>(wait*1000,UINT_MAX));}}
Result cancel(const String&root,const Limits&l,const String&id){if(!valid_limits(l)||!opaque_id(id)||!prepare(root))return error("invalid_input");Lock lock(join(root,"lock"));if(!lock.ok())return error("lock_error");bool complete;auto pending=records(join(root,"pending"),l.scan_max,complete);if(!complete)return error("scan_limit");for(const String&name:pending){String seq,found,raw;DValue r;if(!sequence_name(name,seq,found)||found!=id)continue;if(!read_file(join(root,"pending",name),l.payload_max+l.status_max,raw)||!parse_record(raw,l.payload_max+l.status_max,r)){if(!quarantine(root,l,join(root,"pending"),name))return error("storage_error");return status_locked(root,l,id);}String data=brb_encode(status_value(r,"canceled"));if(data.size()>l.status_max||!publish(join(root,"status"),id+".task",data)||!remove_file(join(root,"pending"),name))return error("storage_error");return ok_status(status_value(r,"canceled"));}auto running=records(join(root,"running"),l.scan_max,complete,false);if(!complete)return error("scan_limit");for(const String&name:running){String seq,found,raw;DValue r;if(!sequence_name(name,seq,found)||found!=id)continue;if(!read_file(join(root,"running",name),l.payload_max+l.status_max,raw)||!parse_record(raw,l.payload_max+l.status_max,r)){if(!quarantine(root,l,join(root,"running"),name))return error("storage_error");return status_locked(root,l,id);}r["cancel_requested"].set_bool(true);String data=brb_encode(r);if(data.size()>l.payload_max+l.status_max||!publish(join(root,"running"),name,data))return error("storage_error");Result out=ok_status(status_value(r,"running"));out.task.lease_id=field(r,"lease_id").to_string();return out;}return status_locked(root,l,id);}

Result cancellation_requests(const String&root,const Limits&l,u64 maximum){if(!valid_limits(l)||!maximum||maximum>l.scan_max||maximum>l.status_max/(id_length*2+32)||!prepare(root))return error("invalid_input");Lock lock(join(root,"lock"));if(!lock.ok())return error("lock_error");bool complete;auto names=records(join(root,"running"),l.scan_max,complete,false);if(!complete)return error("scan_limit");DValue requests;u64 count=0;for(const String&name:names){if(count>=maximum)break;String seq,id,raw;DValue r;if(!sequence_name(name,seq,id)||!read_file(join(root,"running",name),l.payload_max+l.status_max,raw)||!parse_record(raw,l.payload_max+l.status_max,r)){if(!quarantine(root,l,join(root,"running"),name))return error("storage_error");continue;}if(field(r,"cancel_requested").to_bool()&&!field(r,"lease_id").to_string().empty()){requests[id]=field(r,"lease_id").to_string();++count;}}Result out;out.code="ok";out.status["requests"]=requests;out.status["done"].set_bool(false);out.count=count;return out;}

Result recover_worker(const String&root,const Limits&l,const String&lease){if(!valid_limits(l)||(!lease.empty()&&!opaque_id(lease))||!prepare(root))return error("invalid_input");Lock lock(join(root,"lock"));if(!lock.ok())return error("lock_error");bool complete;auto names=records(join(root,"running"),l.scan_max,complete,false);if(!complete)return error("scan_limit");Result out;out.code="ok";for(const String&name:names){String seq,id,raw;DValue r;if(!sequence_name(name,seq,id)||!read_file(join(root,"running",name),l.payload_max+l.status_max,raw)||!parse_record(raw,l.payload_max+l.status_max,r)){if(!quarantine(root,l,join(root,"running"),name))return error("storage_error");++out.count;continue;}if(access(join(join(root,"status"),id+".task").c_str(),F_OK)==0){if(!remove_file(join(root,"running"),name))return error("storage_error");++out.count;continue;}String record_lease=field(r,"lease_id").to_string();if(!record_lease.empty()&&!lease.empty()&&record_lease!=lease)continue;r["failure_code"]=field(r,"cancel_requested").to_bool()?"":"worker_lost";String state=field(r,"cancel_requested").to_bool()?"canceled":"failed",data=brb_encode(status_value(r,state));if(data.size()>l.status_max||!publish(join(root,"status"),id+".task",data)||!remove_file(join(root,"running"),name))return error("storage_error");++out.count;}return out;}
Result reap(const String&root,const Limits&l){if(!valid_limits(l)||!prepare(root))return error("invalid_input");Lock lock(join(root,"lock"));if(!lock.ok())return error("lock_error");bool complete;auto names=records(join(root,"status"),l.scan_max,complete,false);Result out;out.code="ok";u64 wall=0;timespec ts{};if(clock_gettime(CLOCK_REALTIME,&ts))return error("clock_error");wall=(u64)ts.tv_sec*1000+(u64)ts.tv_nsec/1000000;for(const String&name:names){String id,raw;DValue r;if(!status_name(name,id))continue;if(!read_file(join(root,"status",name),l.status_max,raw)||!parse_status(raw,l.status_max,r,id)){if(!publish_failed(root,l,id))return error("storage_error");continue;}u64 completed=0;decimal(field(r,"completed_ms").to_string(),completed);if(wall>=completed&&wall-completed>=l.retention_seconds*1000){if(!remove_file(join(root,"status"),name)||!remove_index(root,id))return error("storage_error");++out.count;}}return out;}
} // namespace task_queue
