#include "tools.h"
#include "parity_manifest.h"
#include "frontend.h"
#include "wasm.h"

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstring>
#include <cctype>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace capy::tools
{
namespace
{
using namespace std::string_view_literals;
std::string read(const std::filesystem::path& path) { std::ifstream in(path, std::ios::binary); if (!in) throw std::runtime_error("could not read " + path.string()); return {std::istreambuf_iterator<char>(in), {}}; }
void write(const std::filesystem::path& path, const std::string& text) { std::ofstream out(path, std::ios::binary | std::ios::trunc); if (!out || !(out << text)) throw std::runtime_error("could not write " + path.string()); }
std::string shell_quote(const std::string& s) { std::string r="'"; for (char c:s) r += c=='\'' ? "'\\''" : std::string(1,c); return r+"'"; }
std::string command_output(const std::string& command) { FILE* f=popen(command.c_str(), "r"); if (!f) throw std::runtime_error("could not run command"); std::array<char, 4096> b; std::string o; while (fgets(b.data(), b.size(), f)) o += b.data(); if (pclose(f) != 0) throw std::runtime_error("command failed: " + command); return o; }

// Small local SHA-256 implementation: capyc must not need Python or libcrypto.
std::string sha256(const std::string& input) {
 static constexpr std::array<std::uint32_t,64> k={0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2};
 auto rr=[](std::uint32_t x,unsigned n){return (x>>n)|(x<<(32-n));}; std::vector<unsigned char> d(input.begin(),input.end()); const std::uint64_t bits=d.size()*8; d.push_back(0x80); while(d.size()%64!=56)d.push_back(0); for(int i=7;i>=0;--i)d.push_back(bits>>(i*8)); std::uint32_t h[]={0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19};
 for(size_t off=0;off<d.size();off+=64){std::uint32_t w[64];for(int i=0;i<16;++i)w[i]=(std::uint32_t(d[off+4*i])<<24)|(std::uint32_t(d[off+4*i+1])<<16)|(std::uint32_t(d[off+4*i+2])<<8)|d[off+4*i+3];for(int i=16;i<64;++i)w[i]=w[i-16]+(rr(w[i-15],7)^rr(w[i-15],18)^(w[i-15]>>3))+w[i-7]+(rr(w[i-2],17)^rr(w[i-2],19)^(w[i-2]>>10));std::uint32_t a=h[0],b=h[1],c=h[2],e=h[4],f=h[5],g=h[6],q=h[7],x=h[3];for(int i=0;i<64;++i){auto t1=q+(rr(e,6)^rr(e,11)^rr(e,25))+((e&f)^((~e)&g))+k[i]+w[i],t2=(rr(a,2)^rr(a,13)^rr(a,22))+((a&b)^(a&c)^(b&c));q=g;g=f;f=e;e=x+t1;x=c;c=b;b=a;a=t1+t2;}h[0]+=a;h[1]+=b;h[2]+=c;h[3]+=x;h[4]+=e;h[5]+=f;h[6]+=g;h[7]+=q;}
 std::ostringstream o;for(auto x:h)o<<std::hex<<std::setw(8)<<std::setfill('0')<<x;return o.str(); }

void embed(const std::string& source, const std::string& header, bool check) { const auto bytes=read(source); std::ostringstream out; out << "// Generated by capyc --embed-stdlib; do not edit.\n#pragma once\n#include <string_view>\nnamespace capy::stdlib {\ninline constexpr char digest[] __attribute__((used)) = \"" << sha256(bytes) << "\";\ninline constexpr unsigned char source[] = {"; for(size_t i=0;i<bytes.size();++i){if(i)out<<',';out<<unsigned(static_cast<unsigned char>(bytes[i]));} out << "};\ninline const std::string_view text(reinterpret_cast<const char*>(source), sizeof(source));\n}\n"; if(check){if(!std::filesystem::is_regular_file(header)||read(header)!=out.str())throw std::runtime_error("stale Capy standard-library embedding: run capyc --embed-stdlib "+source+" "+header);}else if (!std::filesystem::is_regular_file(header) || read(header) != out.str()) write(header,out.str()); }

void stdlib_signatures(const std::string& path)
{
	const std::string source = read(path);
	Program program = parse(source, path);
	for (Expr* expression : program.items)
	{
		auto* function = dynamic_cast<Function*>(expression);
		if (!function || function->host || function->name.starts_with("__"))
			continue;
		std::string declaration = source.substr(function->location.offset, function->body->location.offset - function->location.offset);
		std::string normalized;
		bool space = false;
		for (char character : declaration)
			if (std::isspace(static_cast<unsigned char>(character)))
				space = !normalized.empty();
			else
			{
				if (space)
					normalized.push_back(' ');
				normalized.push_back(character);
				space = false;
			}
		while (!normalized.empty() && normalized.back() == ' ')
			normalized.pop_back();
		std::cout << function->name << '\t' << normalized << '\n';
	}
	static constexpr std::pair<std::string_view, std::string_view> language_forms[] = {
		{"0_DValue", "type dval"}, {"0_Request", "type request"}, {"0_String", "type string"},
		{"0_StringList", "type dval (list of strings)"}, {"0_StringMap", "type dval (map of strings)"},
		{"1_INIT", "function INIT"}, {"1_INIT", "function INIT(request : request)"},
		{"1_ONCE", "function ONCE"}, {"1_ONCE", "function ONCE(request : request)"},
		{"1_CLI", "function CLI"}, {"1_CLI", "function CLI(request : request)"},
		{"1_RENDER", "function RENDER"}, {"1_RENDER", "function RENDER(request : request)"},
		{"1_RENDER", "function RENDER:NAME"}, {"1_RENDER", "function RENDER:NAME(request : request)"},
		{"1_COMPONENT", "function COMPONENT"}, {"1_COMPONENT", "function COMPONENT(request : request)"},
		{"1_COMPONENT", "function COMPONENT:NAME"}, {"1_COMPONENT", "function COMPONENT:NAME(request : request)"},
		{"1_WS", "function WS"}, {"1_WS", "function WS(request : request)"},
		{"2_DValue_each", "for key, value = input { ... }"},
		{"2_DValue_has", "dval_has(value : dval, key : string) bool"},
		{"2_DValue_operator_index", "value[key]"},
	};
	for (const auto& [page, declaration] : language_forms)
		std::cout << "page:" << page << '\t' << declaration << '\n';
}

std::string category(std::string_view n) { auto starts=[&](std::initializer_list<std::string_view> xs){for(auto x:xs)if(n.starts_with(x))return true;return false;}; if(n.starts_with("1_"))return "handler/lifecycle";if(starts({"0_DValue","2_DValue"}))return "structured values";if(starts({"0_String","2_String"}))return "strings/collections";if(starts({"0_Request","2_Request","request_","cli_","csrf_","session_","redirect"}))return "request/response";if(starts({"component","unit","units_"}))return "unit/component";if(starts({"file_","dir_","path_","cwd_","ls","mkdir","basename","dirname","expand_path"}))return "filesystem";if(starts({"mysql_","sqlite_","memcache_"}))return "data/cache";if(starts({"ws_","socket_","http_"}))return "network/websocket";if(starts({"job_","task","server_","shell_","process_"}))return "jobs/process";if(starts({"sha","hmac_","base64_","crypto_","password_","random_","gen_","draw_"}))return "crypto/random";if(starts({"json_","xml_","yaml_","regex_","markdown_","uri_","html_","brb_"}))return "codecs/text";if(starts({"zip_","gz_"}))return "archive";if(n.starts_with("3_"))return "documentation/C++";return "core utility"; }
const parity::Evidence* find(const auto& entries, std::string_view name) { for(const auto& e:entries)if(e.name==name)return &e;return nullptr; }
void manifest(const std::string& output) { const std::filesystem::path root=std::filesystem::current_path(); const std::string driver=read(root/"scripts/test_capy_phase1.sh")+read(root/"scripts/test_capy_websocket.cpp")+read(root/"site/tests/capy-serve-http-caller.uce"); auto check_evidence = [&](const auto& entries) { for(const auto& e:entries){const auto p=root/e.path;if(!std::filesystem::is_regular_file(p)||read(p).find(e.marker)==std::string::npos)throw std::runtime_error(std::string(e.name)+": missing parity evidence");if(e.path.starts_with("site/tests/")&&driver.find(p.filename().string())==std::string::npos)throw std::runtime_error(std::string(e.name)+": parity fixture is not wired into runtime driver");} }; check_evidence(parity::supported); check_evidence(parity::partial); struct R{std::string n,g,s,note;};std::vector<R> rows;std::map<std::string,int> counts;for(const auto& d:std::filesystem::directory_iterator(root/"site/doc/pages")){if(d.path().extension()!=".txt")continue;auto n=d.path().stem().string();std::string status="missing",note="No native Capy binding in the checked compiler surface.";if(auto e=find(parity::missing_notes,n))note=std::string(e->marker);if(std::find(parity::cpp_specific.begin(),parity::cpp_specific.end(),n)!=parity::cpp_specific.end())status="cpp-specific",note="No Capy runtime equivalent required.";else if(auto e=find(parity::unsupported_by_design,n))status="unsupported-by-design",note=std::string(e->marker);else if(auto e=find(parity::supported,n))status="supported",note="Runtime evidence: `"+std::string(e->path)+"`.";else if(n.starts_with("1_"))status="export-only",note="Capy emits the handler export; lifecycle behavior still needs parity acceptance.";else if(auto e=find(parity::partial,n))status="partial",note="Partial runtime evidence: `"+std::string(e->path)+"`; the documented convenience API remains incomplete.";rows.push_back({n,category(n),status,note});counts[status]++;}std::sort(rows.begin(),rows.end(),[](auto&a,auto&b){std::string x=a.n,y=b.n;std::transform(x.begin(),x.end(),x.begin(),::tolower);std::transform(y.begin(),y.end(),y.begin(),::tolower);return x<y;});std::ostringstream o;o<<"# Capy / C++ `.uce` capability parity manifest\n\nGenerated by `capyc --parity-manifest` from `site/doc/pages/`.\nThis inventory is a progress boundary: `partial`, `export-only`, and `missing` are not parity.\n\nDocumented pages: **"<<rows.size()<<"**. ";bool first=true;for(auto&[k,v]:counts){if(!first)o<<", ";first=false;o<<k<<": **"<<v<<"**";}o<<"\n\n## Binding boundary\n\n- Pure, common value operations (strings, numeric conversion, collection access) lower directly in Capy when compact and faster than a call.\n- Request/response, sessions, WebSockets, and other current-workspace operations use narrow typed core adapters; Capy never reads C++ layouts.\n- Structured policy-heavy operations already represented by DValues (HTTP client, jobs, regex/codecs, unit administration) use bounded copied BRRB capability adapters rather than `unit_call` shims.\n- Filesystem, sockets, shell, cache, database, and archive operations reuse Bearer's existing core/host policy. Opaque resources become typed numeric handles only after u64 support; no direct OS imports are added to side units.\n- `unit_call` remains application composition, not a substitute for missing standard bindings.\n\n| Documented capability | Category | Status | Evidence/remaining work |\n|---|---|---|---|\n";for(auto&r:rows)o<<"| `"<<r.n<<"` | "<<r.g<<" | **"<<r.s<<"** | "<<r.note<<" |\n";if(output.empty())std::cout<<o.str();else write(output,o.str()); }

void source_map(const std::string& dwarfdump, const std::string& wasm, const std::string& module, const std::string& output)
{
	std::istringstream in(command_output(shell_quote(dwarfdump) + " --debug-line " + shell_quote(wasm)));
	std::map<unsigned, std::string> dirs;
	std::map<unsigned, std::pair<std::string, unsigned>> files;
	struct Row { std::string address; unsigned line, column, file; };
	std::vector<Row> rows;
	unsigned current = 0;
	std::string line;
	while (std::getline(in, line))
	{
		auto bracket_id = [&](const char* prefix, unsigned& value) {
			if (!line.starts_with(prefix)) return false;
			const auto end = line.find(']', std::strlen(prefix));
			if (end == std::string::npos) return false;
			value = std::stoul(line.substr(std::strlen(prefix), end - std::strlen(prefix)));
			return true;
		};
		unsigned id;
		if (bracket_id("include_directories[", id)) { const auto p = line.find(" = "); if (p != std::string::npos) { std::istringstream q(line.substr(p + 3)); std::string value; q >> std::quoted(value); dirs[id] = value; } continue; }
		if (bracket_id("file_names[", id) && line.ends_with(":")) { current = id; continue; }
		auto stripped = line; stripped.erase(0, stripped.find_first_not_of(" \t"));
		if (current && stripped.starts_with("name: ")) { std::istringstream q(stripped.substr(6)); std::string value; q >> std::quoted(value); files[current] = {value, 0}; continue; }
		if (current && stripped.starts_with("dir_index: ")) { files[current].second = std::stoul(stripped.substr(11)); continue; }
		std::istringstream row(stripped); std::string address; unsigned line_no, column, file;
		if ((row >> address >> line_no >> column >> file) && address.starts_with("0x")) rows.push_back({address.substr(2), line_no, column, file});
	}
	std::ostringstream out;
	out << "BEARER_SOURCE_MAP_V1\t" << module << std::endl;
	for (auto& [id, f] : files) { auto path = std::filesystem::path(f.first); if (!path.is_absolute()) path = dirs[f.second] / path; path = std::filesystem::absolute(path).lexically_normal(); const auto text = path.string(); if (text.find_first_of("\t\r\n") != std::string::npos) throw std::runtime_error("source-map path contains a control character"); out << "F\t" << id << '\t' << text << std::endl; }
	for (auto& r : rows) out << "L\t" << r.address << '\t' << r.file << '\t' << r.line << '\t' << r.column << std::endl;
	write(output, out.str());
}

void check_unit(const std::string& wasm, const std::string& abi, const std::string& nm) { auto text=read(wasm); wasm::Bytes bytes(text.begin(),text.end());auto v=wasm::validate_bearer_unit(bytes,{.bearer_abi_version=abi});if(!v.valid)throw std::runtime_error(v.error);for(auto&i:v.imports)if(i.module.starts_with("wasi_") || (i.module != "env" && !i.module.starts_with("GOT.")))throw std::runtime_error("unexpected import module "+i.module+"."+i.name);const auto symbols=command_output(shell_quote(nm)+" --defined-only "+shell_quote(wasm));for(std::istringstream in(symbols);in;){std::string line;std::getline(in,line);auto p=line.find_last_of(" \t");auto s=line.substr(p==std::string::npos?0:p+1);if(s=="bearer_alloc"||s=="bearer_free"||s.starts_with("_Znwm")||s.starts_with("_Znam")||s.starts_with("_ZdlPv")||s.starts_with("_ZdaPv"))throw std::runtime_error("forbidden allocator definition "+s);} }
}

int run(int argc,char** argv) { try { if(argc<2)return -1;const std::string a=argv[1];if((a=="--embed-stdlib"||a=="--check-stdlib")&&argc==4){embed(argv[2],argv[3],a=="--check-stdlib");return 0;}if(a=="--parity-manifest"&&(argc==2||argc==3)){manifest(argc==3?argv[2]:"");return 0;}if(a=="--stdlib-signatures"&&argc==3){stdlib_signatures(argv[2]);return 0;}if(a=="--build-source-map"&&argc==6){source_map(argv[2],argv[3],argv[4],argv[5]);return 0;}if(a=="--check-unit"&&(argc==4||argc==6)){check_unit(argv[2],argv[3],argc==6&&std::string(argv[4])=="--llvm-nm"?argv[5]:(std::filesystem::exists("/opt/wasi-sdk/bin/llvm-nm") ? "/opt/wasi-sdk/bin/llvm-nm" : "llvm-nm"));return 0;}}catch(const std::exception&e){std::cerr<<"capyc: "<<e.what()<<'\n';return 1;}return -1; }
}
