#!/usr/bin/env python3
"""Build the checked Capy/.uce public capability parity inventory."""

from collections import Counter
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent
PAGES = ROOT / "site/doc/pages"

SUPPORTED = {
    "print", "unit_render", "2_DValue_each", "2_DValue_has", "2_DValue_operator_index",
}
PARTIAL = {
    "0_Request", "2_Request_set_status", "cli_arg", "cli_input", "component_render",
    "request_base_url", "request_context_params", "request_query_path",
    "request_query_route", "request_route_from_raw_path", "request_script_url", "unit_call",
    "2_DValue_get_type_name", "2_DValue_is_array", "2_DValue_is_list", "2_DValue_key",
    "2_DValue_keys", "2_DValue_to_bool", "2_DValue_to_string", "2_DValue_values",
}
CPP_SPECIFIC = {"3_Blocked functions", "3_C++ Preprocessor", "3_Coming from React", "3_Documentation format"}


def category(name: str) -> str:
    if name.startswith("1_"):
        return "handler/lifecycle"
    if name.startswith(("0_DValue", "2_DValue")):
        return "structured values"
    if name.startswith(("0_String", "2_String")):
        return "strings/collections"
    if name.startswith(("0_Request", "2_Request", "request_", "cli_", "csrf_", "session_", "redirect")):
        return "request/response"
    if name.startswith(("component", "unit", "units_")):
        return "unit/component"
    if name.startswith(("file_", "dir_", "path_", "cwd_", "ls", "mkdir", "basename", "dirname", "expand_path")):
        return "filesystem"
    if name.startswith(("mysql_", "sqlite_", "memcache_")):
        return "data/cache"
    if name.startswith(("ws_", "socket_", "http_")):
        return "network/websocket"
    if name.startswith(("job_", "task", "server_", "shell_", "process_")):
        return "jobs/process"
    if name.startswith(("sha", "hmac_", "base64_", "crypto_", "password_", "random_", "gen_", "draw_")):
        return "crypto/random"
    if name.startswith(("json_", "xml_", "yaml_", "regex_", "markdown_", "uri_", "html_", "brb_")):
        return "codecs/text"
    if name.startswith(("zip_", "gz_")):
        return "archive"
    if name.startswith("3_"):
        return "documentation/C++"
    return "core utility"


def classify(name: str) -> tuple[str, str]:
    if name in CPP_SPECIFIC:
        return "cpp-specific", "No Capy runtime equivalent required."
    if name.startswith("1_"):
        return "export-only", "Capy emits the handler export; lifecycle behavior still needs parity acceptance."
    if name in SUPPORTED:
        return "supported", "Native Capy equivalent is runtime-tested."
    if name in PARTIAL:
        return "partial", "Underlying data/outcome is available, but the documented convenience API is incomplete."
    return "missing", "No native Capy binding in the checked compiler surface."


def render() -> str:
    rows = []
    for page in sorted(PAGES.glob("*.txt"), key=lambda path: path.name.lower()):
        name = page.stem
        status, note = classify(name)
        rows.append((name, category(name), status, note))
    counts = Counter(row[2] for row in rows)
    lines = [
        "# Capy / C++ `.uce` capability parity manifest",
        "",
        "Generated by `scripts/build_capy_parity_manifest.py` from `site/doc/pages/`.",
        "This inventory is a progress boundary: `partial`, `export-only`, and `missing` are not parity.",
        "",
        f"Documented pages: **{len(rows)}**. " + ", ".join(f"{key}: **{counts[key]}**" for key in sorted(counts)),
        "",
        "| Documented capability | Category | Status | Evidence/remaining work |",
        "|---|---|---|---|",
    ]
    lines.extend(f"| `{name}` | {group} | **{status}** | {note} |" for name, group, status, note in rows)
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    content = render()
    if len(sys.argv) == 2:
        Path(sys.argv[1]).write_text(content)
    else:
        sys.stdout.write(content)
