#!/usr/bin/env python3
import argparse
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE_SYMBOLS = {
    "2_DValue_set": ["dval_set"],
    "request_context_params": [
        "request_context", "request_script_url", "request_base_url", "request_query_path", "request_query_route",
    ],
}


def quote(text: str) -> str:
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def compiler_signatures(capyc: Path) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    output = subprocess.check_output(
        [str(capyc), "--stdlib-signatures", "src/capy/stdlib.capy"], cwd=ROOT, text=True
    )
    signatures: dict[str, list[str]] = {}
    pages: dict[str, list[str]] = {}
    for line in output.splitlines():
        symbol, declaration = line.split("\t", 1)
        if symbol.startswith("page:"):
            pages.setdefault(symbol[5:], []).append(declaration)
        else:
            signatures.setdefault(symbol, []).append(declaration)
    return signatures, pages


def supported_pages() -> list[tuple[str, str]]:
    source = (ROOT / "src/capy/parity_manifest.h").read_text()
    body = source.split("supported{{", 1)[1].split("}};", 1)[0]
    return [(name, marker) for name, _path, marker in re.findall(r'\{"([^"]+)","([^"]*)","([^"]*)"\}', body)]


def generate(capyc: Path) -> str:
    signatures, compiler_pages = compiler_signatures(capyc)
    pages: dict[str, list[str]] = {}
    for page, marker in supported_pages():
        if page == "3_Documentation format":
            pages[page] = []
            continue
        if page in compiler_pages:
            pages[page] = compiler_pages[page]
            continue
        if page in PAGE_SYMBOLS:
            pages[page] = [declaration for symbol in PAGE_SYMBOLS[page] for declaration in signatures[symbol]]
            continue
        match = re.match(r"([A-Za-z_][A-Za-z0-9_]*)\(", marker)
        if not match or match.group(1) not in signatures:
            raise RuntimeError(f"{page}: no Capy signature mapping for evidence marker {marker!r}")
        pages[page] = signatures[match.group(1)]

    lines = [
        "// Generated by scripts/generate_capy_doc_signatures.py. Do not edit.",
        "#pragma once",
        "#include <string_view>",
        "",
        "struct DocCapySignature { std::string_view page, declaration; };",
        "inline constexpr DocCapySignature doc_capy_signatures[] = {",
    ]
    for page in sorted(pages, key=str.lower):
        for declaration in pages[page]:
            lines.append(f"\t{{{quote(page)}, {quote(declaration)}}},")
    lines.extend([
        "};",
        "",
        "DValue doc_capy_signature_lines(String page)",
        "{",
        "\tDValue lines;",
        "\tfor(const auto& entry : doc_capy_signatures)",
        "\t{",
        "\t\tif(entry.page == std::string_view(page))",
        "\t\t\tlines.push_back(String(entry.declaration));",
        "\t\telse if(lines.size() > 0)",
        "\t\t\tbreak;",
        "\t}",
        "\treturn(lines);",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--capyc", type=Path, default=ROOT / "bin/capyc")
    parser.add_argument("--output", type=Path, default=ROOT / "site/doc/lib/capy_signatures.generated.h")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate(args.capyc.resolve())
    if args.check:
        if not args.output.is_file() or args.output.read_text() != content:
            raise SystemExit("generated Capy documentation signatures are stale")
    elif not args.output.is_file() or args.output.read_text() != content:
        args.output.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
