#!/usr/bin/env python3
import argparse
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE_SYMBOLS = {
    "clear": ["clear"],
    "delete": ["delete"],
    "get": ["get"],
    "get_by_path": ["get_by_path"],
    "get_or_create": ["get_or_create"],
    "get_type_name": ["get_type_name"],
    "is_array": ["is_array"],
    "is_list": ["is_list"],
    "keys": ["keys"],
    "pop": ["pop"],
    "push": ["push"],
    "set": ["set"],
    "values": ["values"],
    "session_set": ["session_set"],
    "session_remove": ["session_remove"],
    "call": ["call"],
    "bool": ["bool"],
    "s32": ["s32"],
    "s64": ["s64"],
    "u64": ["u64"],
    "f64": ["f64"],
    "string": ["string"],
}

PAGE_SIGNATURES = {
    "has": ["has(value : dval, key : string) bool"],
    "length": [
        "function length(value : string) s32",
        "function length(value : markup) s32",
        "function length(value : dval) s32",
        "function length(value : [T]) s32",
    ],
    "trap": ["function trap()"],
    "mysql_info": ["function mysql_info(handle : u64, key : string) dval"],
    "sqlite_info": ["function sqlite_info(handle : u64, key : string) dval"],
    "posix_info": ["function posix_info(key : string, value : dval) dval"],
    "clone": ["function clone(value : string) string"],
    "dval": [
        "function dval(value : string) dval",
        "function dval(value : s32) dval",
        "function dval(value : s64) dval",
        "function dval(value : u64) dval",
        "function dval(value : f64) dval",
        "function dval(value : bool) dval",
        "function dval(value : dval) dval",
    ],
}


def quote(text: str) -> str:
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def compiler_signatures(capyc: Path) -> tuple[dict[str, list[str]], dict[str, list[str]]]:
    output = subprocess.check_output(
        [str(capyc), "--stdlib-signatures", "src/capy/stdlib.capy"], cwd=ROOT, text=True
    )
    signatures: dict[str, list[str]] = {}
    pages: dict[str, list[str]] = {}
    for line in output.splitlines():
        symbol, declaration = line.split("\t", 1)
        if symbol.startswith("page:"):
            pages.setdefault(symbol[5:], []).append(declaration)
        else:
            signatures.setdefault(symbol, []).append(declaration)
    return signatures, pages


def supported_pages() -> list[tuple[str, str]]:
    source = (ROOT / "src/capy/parity_manifest.h").read_text()
    body = source.split("supported{{", 1)[1].split("}};", 1)[0]
    return [(name, marker) for name, _path, marker in re.findall(r'\{"([^"]+)","([^"]*)","([^"]*)"\}', body)]


def generate(capyc: Path) -> str:
    signatures, compiler_pages = compiler_signatures(capyc)
    pages: dict[str, list[str]] = {}
    for page, marker in supported_pages():
        if page in compiler_pages:
            pages[page] = compiler_pages[page]
            continue
        if page in PAGE_SYMBOLS:
            pages[page] = [declaration for symbol in PAGE_SYMBOLS[page] for declaration in signatures[symbol]]
            continue
        if page in PAGE_SIGNATURES:
            pages[page] = PAGE_SIGNATURES[page]
            continue
        match = re.match(r"([A-Za-z_][A-Za-z0-9_]*)\(", marker)
        if not match or match.group(1) not in signatures:
            raise RuntimeError(f"{page}: no Capy signature mapping for evidence marker {marker!r}")
        pages[page] = signatures[match.group(1)]

    lines = [
        "// Generated by scripts/generate_capy_doc_signatures.py. Do not edit.",
        "#pragma once",
        "#include <string_view>",
        "",
        "struct DocCapySignature { std::string_view page, declaration; };",
        "inline constexpr DocCapySignature doc_capy_signatures[] = {",
    ]
    for page in sorted(pages, key=str.lower):
        for declaration in pages[page]:
            lines.append(f"\t{{{quote(page)}, {quote(declaration)}}},")
    lines.extend([
        "};",
        "",
        "DValue doc_capy_signature_lines(String page)",
        "{",
        "\tDValue lines;",
        "\tfor(const auto& entry : doc_capy_signatures)",
        "\t{",
        "\t\tif(entry.page == std::string_view(page))",
        "\t\t\tlines.push_back(String(entry.declaration));",
        "\t\telse if(lines.size() > 0)",
        "\t\t\tbreak;",
        "\t}",
        "\treturn(lines);",
        "}",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--capyc", type=Path, default=ROOT / "bin/capyc")
    parser.add_argument("--output", type=Path, default=ROOT / "site/doc/lib/capy_signatures.generated.h")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = generate(args.capyc.resolve())
    if args.check:
        if not args.output.is_file() or args.output.read_text() != content:
            raise SystemExit("generated Capy documentation signatures are stale")
    elif not args.output.is_file() or args.output.read_text() != content:
        args.output.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
