#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
	systemctl daemon-reload >/dev/null 2>&1 || true
	if [ "$1" = "configure" ]; then
		systemctl enable bearer.socket bearer.service >/dev/null 2>&1 || true
		systemctl start bearer.socket >/dev/null 2>&1 || true
		systemctl restart bearer.service >/dev/null 2>&1 || true
	fi
fi

exit 0
